### ISSUE TITLE
Stable working version using dep.

### ISSUE THREAD

**Issue by MaximeAubanel** [gorgonia/gorgonia#283]
Hello there,

I'm trying to use gorgonia for the first time and I'm really struggling to have a proper working environment.

**OS**: Mojave 10.14.3
**Go version**: go1.12.4
**dep version**: 0.5.1

My problem is the following. I'm trying to run the first example program (z = x + y equation) but can't make it work at all due to vendoring issues.

First of all, that's what my Gopkg.toml looked like.

```toml
required = ["github.com/gorgonia/gorgonia"]

[prune]
  unused-packages = true
  go-tests = true

[[constraint]]
  name = "github.com/gorgonia/gorgonia"
  version = "0.9.1"
```

Then I run `dep ensure` and I got an error:

```
Solving failure: No versions of gorgonia.org/cu met constraints:
	v0.9.0-beta: Could not introduce gorgonia.org/cu@v0.9.0-beta, as it is not allowed by constraint ^0.8.0 from project github.com/gorgonia/gorgonia.
	v0.8.0: Could not introduce gorgonia.org/cu@v0.8.0, as its subpackage gorgonia.org/cu/dnn is missing. (Package is required by github.com/gorgonia/gorgonia@v0.9.1.)
	master: Could not introduce gorgonia.org/cu@master, as it is not allowed by constraint ^0.8.0 from project github.com/gorgonia/gorgonia.
	chad: Could not introduce gorgonia.org/cu@chad, as it is not allowed by constraint ^0.8.0 from project github.com/gorgonia/gorgonia.
	v0.9.0-working: Could not introduce gorgonia.org/cu@v0.9.0-working, as it is not allowed by constraint ^0.8.0 from project github.com/gorgonia/gorgonia.
```

Then I tried using the master branch.

```toml
required = ["github.com/gorgonia/gorgonia"]

[prune]
  unused-packages = true
  go-tests = true

[[constraint]]
  name = "github.com/gorgonia/gorgonia"
  branch = "master"
```

`dep ensure` work here. But when I run the program using `go run main.go` I got an error:

```
# github.com/WhoIsWriting/vendor/gorgonia.org/gorgonia
vendor/gorgonia.org/gorgonia/node.go:437:16: n.shape.CalcStrides undefined (type tensor.Shape has no field or method CalcStrides)
vendor/gorgonia.org/gorgonia/utils.go:147:28: undefined: tensor.InfChecker
vendor/gorgonia.org/gorgonia/utils.go:190:28: undefined: tensor.NaNChecker
```

I tried using other branch like `master-working` or even old version like 0.8.4 but they all failed with either a `dep ensure` error or an error in the vendor folder like I just mentioned in the error snippet above.

What am I missing/what should I do ?
